# Generated by Django 5.1.6 on 2025-02-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
